"use client";
import { useReducer, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check, Coins, Frown, PartyPopper, PieChart, Plus, RotateCcw, Spade, Trophy, Users, X } from 'lucide-react';
import { initialState, reducer, poolOf, evenShares, parseMoney, type Opponent } from './game';
const money = (cents: number) => (cents < 0 ? '−' : '') + (Math.abs(cents) / 100).toLocaleString('en-US', { maximumFractionDigits: 2 });
const initials = (name: string) => name.split(/\s+/).map(s => s[0]).slice(0, 2).join('').toUpperCase();
export default function Home() {
 const [state, dispatch] = useReducer(reducer, initialState);
 const [opponents, setOpponents] = useState<Opponent[]>([]);
 const [name, setName] = useState(''); const [nameError, setNameError] = useState('');
 const flash = state.resultFlash;
 const pool = poolOf(state.opponents), needsDeposit = pool === 0;
 const bet = parseMoney(state.bet), deposit = parseMoney(state.deposit);
 const validBet = state.opponents.some(p => p.id === state.selected) && bet !== null && bet > 0 && bet <= pool && !needsDeposit;
 const shares = evenShares(pool, state.opponents.length);
 const addOpponent = (event: React.FormEvent) => { event.preventDefault(); const clean = name.trim(); if (!clean) return setNameError('Enter an opponent’s name.'); if (opponents.some(p => p.name.toLowerCase() === clean.toLowerCase())) return setNameError('That name is already at the table.'); setOpponents([...opponents, { id: crypto.randomUUID(), name: clean, balance: 0 }]); setName(''); setNameError(''); };
 return <div className={`app-shell ${flash?.outcome === 'lose' ? 'shake' : ''}`}>
 {flash && <div className={`result-flash ${flash.outcome}`} key={flash.token} role="status" aria-live="assertive" onAnimationEnd={() => dispatch({ type: 'clearFlash' })}>
  <div className="result-flash-card">
   {flash.outcome === 'win' ? <PartyPopper size={40}/> : <Frown size={40}/>}
   <strong>{flash.playerName} {flash.outcome === 'win' ? 'wins' : 'loses'}!</strong>
   <span>{flash.outcome === 'win' ? '+' : '−'}{money(flash.amount)}</span>
  </div>
  {flash.outcome === 'win' && <div className="confetti" aria-hidden="true">{Array.from({ length: 16 }).map((_, i) => <i key={i} style={{ '--i': i } as React.CSSProperties}/>)}</div>}
 </div>}
 <header className="topbar"><Link href="/" className="brand"><Spade size={25} fill="currentColor"/> POOLROOM<span>.</span></Link><div className="header-note">THE GAME. ALL ACCOUNTED FOR.</div><span className="session-label">{state.started ? 'Table in session' : 'New table'}</span></header>
 <main><div className="page-heading"><div><p className="eyebrow">YOUR TABLE, YOUR GAME</p><h1>{state.started ? 'Let’s play.' : 'Bring your opponents.'}</h1><p className="muted">{state.started ? 'Pick a player. Place a bet. Keep the balance.' : 'Add everyone at the table, then get the game going.'}</p></div><div className="step-indicator"><span className={!state.started ? 'current' : 'complete'}>{state.started ? <Check size={14}/> : '1'}</span> Setup <i/><span className={state.started ? 'current' : ''}>2</span> Play</div></div>
 {!state.started ? <div className="setup-grid"><section className="panel setup-panel"><div className="section-heading"><div><p className="eyebrow">01 / THE LINEUP</p><h2>Who’s playing?</h2></div><Users className="gold" size={25}/></div><form onSubmit={addOpponent}><label htmlFor="opponent-name">Opponent name</label><div className="input-row"><input id="opponent-name" value={name} maxLength={40} onChange={e => setName(e.target.value)} placeholder="e.g. James" autoComplete="off"/><button className="gold-button" type="submit"><Plus size={18}/> Add</button></div></form>{nameError && <p className="error" role="alert">{nameError}</p>}<div className="lineup-heading"><span>OPPONENTS <b>{opponents.length}</b></span><span>STARTING BALANCE</span></div><div className="setup-list">{opponents.length ? opponents.map((p,i) => <div className="setup-person" key={p.id}><span className={`avatar color-${i%4}`}>{initials(p.name)}</span><strong>{p.name}</strong><span className="balance">0</span><button className="icon-button" onClick={() => setOpponents(opponents.filter(o => o.id !== p.id))} aria-label={`Remove ${p.name}`}><X size={17}/></button></div>) : <div className="empty-lineup"><Users size={30}/><p>The table is open.</p><span>Add your first opponent above.</span></div>}</div><button className="gold-button start-button" disabled={!opponents.length} onClick={() => dispatch({ type:'start', opponents })}>Start game <ArrowRight size={19}/></button><p className="footnote">Everyone starts at 0. Collect the first deposit next.</p></section><aside className="setup-art"><div className="felt-ring"><span className="corner-suit">♠</span><div className="chip chip-back"/><div className="chip chip-front"><Spade size={44} fill="currentColor"/></div><p className="table-wordmark">A SEAT AT THE TABLE</p><h2>Good company.<br/>A great game.</h2><div className="suits">♠ <span>♥</span> ♣ <span>♦</span></div></div><p>One pool. Every player. Every move.</p></aside></div> :
 <><div className="game-layout"><aside className="panel opponents-panel"><div className="section-heading"><h2>Opponents</h2><span className="count">{state.opponents.length}</span></div><p className="muted small">Select who’s playing this turn.</p><div className="roster-labels"><span>PLAYER</span><span>BALANCE</span></div><div className="roster">{state.opponents.map((p,i) => <button key={p.id} className={`player-row ${state.selected === p.id ? 'selected' : ''}`} onClick={() => dispatch({ type:'select', id:p.id })} aria-pressed={state.selected === p.id}><span className={`avatar color-${i%4}`}>{initials(p.name)}</span><span className="player-name">{p.name}{state.selected === p.id && <small>Playing this turn</small>}</span><strong className={p.balance < 0 ? 'negative' : p.balance > 0 ? 'positive' : ''}>{p.balance > 0 ? '+' : ''}{money(p.balance)}</strong></button>)}</div><div className="balance-total"><span>Total player balance</span><strong>{money(-pool)}</strong></div><p className="footnote">Player balances + pool = 0</p></aside><div className="table-column"><section className="pool-card"><div className="pool-top"><span><Coins size={17}/> THE POOL</span><span className="pool-status">{needsDeposit ? 'Awaiting deposits' : 'Ready to play'}</span></div><div className="pool-value" aria-live="polite">{money(pool)}</div><p>Current money available</p><div className="pool-decoration" aria-hidden="true">♠</div><div className="pool-bottom"><span>{state.opponents.length} opponents at the table</span><span>♠ &nbsp; ♥ &nbsp; ♣ &nbsp; ♦</span></div></section>
 <section className={`panel deposit-panel ${needsDeposit ? 'deposit-required' : ''}`}><div><h2>Bet Deposit</h2><p className="muted small">{needsDeposit ? 'Collect from every opponent to open the pool.' : 'Add the same amount from every opponent.'}</p></div><form onSubmit={e => {e.preventDefault();dispatch({type:'deposit'});}}><label className="sr-only" htmlFor="deposit">Bet Deposit per opponent</label><div className="input-row"><input id="deposit" inputMode="decimal" value={state.deposit} placeholder="Amount per player" onChange={e => dispatch({type:'input',field:'deposit',value:e.target.value})}/><button className="gold-button" disabled={deposit === null || deposit <= 0}><Plus size={17}/>Add</button></div></form></section>
 <section className="panel play-panel"><div className="section-heading"><div><p className="eyebrow">THE NEXT MOVE</p><h2>Place a bet</h2></div><span className="turn-badge">{needsDeposit ? 'Deposit required' : 'Your table is live'}</span></div><div className="bet-fields"><div><label htmlFor="current-player">Playing opponent</label><select id="current-player" value={state.selected} onChange={e => dispatch({type:'select',id:e.target.value})}><option value="">Select an opponent</option>{state.opponents.map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select></div><div><label htmlFor="bet">Bet Amount <span>Max {money(pool)}</span></label><input id="bet" inputMode="decimal" placeholder="0.00" disabled={needsDeposit} value={state.bet} onChange={e => dispatch({type:'input',field:'bet',value:e.target.value})}/></div></div><p className={state.bet && (bet === null || bet <= 0 || bet > pool) && !needsDeposit ? 'error bet-hint' : 'muted small bet-hint'}>{needsDeposit ? 'Add a deposit above before recording the next result.' : state.bet && (bet === null || bet <= 0) ? 'Enter a positive amount with up to two decimal places.' : bet !== null && bet > pool ? 'The bet cannot exceed the current pool.' : 'Record the result from the selected opponent’s perspective.'}</p><div className="result-buttons"><button className="win-button" disabled={!validBet} onClick={() => dispatch({type:'result',outcome:'win'})}><Trophy size={20}/> Win <span>Player receives the bet</span></button><button className="lose-button" disabled={!validBet} onClick={() => dispatch({type:'result',outcome:'lose'})}><X size={21}/> Lose <span>Player pays into the pool</span></button></div><div className="action-footer"><p role="status">{state.error || state.message || 'The table is ready for its first deposit.'}</p><button className="undo-button" disabled={!state.history.length} onClick={() => dispatch({type:'undo'})}><RotateCcw size={16}/> Undo</button></div></section></div></div>
 <section className="panel settlement-panel"><div className="section-heading"><div><p className="eyebrow">SPLIT IT UP</p><h2>Settlement preview</h2></div><PieChart className="gold" size={24}/></div><p className="muted small">See what happens if the current pool were split evenly across every opponent right now.</p><div className="settlement-table-wrap"><table className="settlement-table"><thead><tr><th>Opponent</th><th>Current balance</th><th>Even share of pool</th><th>Balance after split</th></tr></thead><tbody>{state.opponents.map((p,i) => <tr key={p.id} className={state.selected === p.id ? 'selected' : ''}><td><span className={`avatar tiny color-${i%4}`}>{initials(p.name)}</span>{p.name}</td><td className={p.balance < 0 ? 'negative' : p.balance > 0 ? 'positive' : ''}>{p.balance > 0 ? '+' : ''}{money(p.balance)}</td><td className="positive">+{money(shares[i] ?? 0)}</td><td className={(p.balance + (shares[i] ?? 0)) < 0 ? 'negative' : (p.balance + (shares[i] ?? 0)) > 0 ? 'positive' : ''}>{(p.balance + (shares[i] ?? 0)) > 0 ? '+' : ''}{money(p.balance + (shares[i] ?? 0))}</td></tr>)}</tbody><tfoot><tr><td>Total</td><td>{money(-pool)}</td><td className="positive">+{money(pool)}</td><td>{money(0)}</td></tr></tfoot></table></div><div className="settlement-footer"><p className="muted small">{needsDeposit ? 'The pool is empty — nothing to split yet.' : `Splitting divides ${money(pool)} into ${state.opponents.length} even shares.`}</p><button className="gold-button" disabled={needsDeposit} onClick={() => dispatch({type:'split'})}><PieChart size={17}/> Split pool evenly</button></div></section></>}
 <footer className="page-footer"><span><Spade size={13}/> POOLROOM</span><span>Keep the game fair. Keep the numbers clear.</span></footer></main></div>;
}
